### ISSUE TITLE
Support for CHD and RVZ archives ?

### ISSUE THREAD

**Issue by nixxou** [fraganator/archive-cache-manager#18]
It's maybe overkill since CHD and RVZ allow fast decompression and can be fed to emulators as if, but i think it could be an interesting option, especially while this feature request is not filled : https://github.com/fraganator/archive-cache-manager/issues/12 
CHD can be decrypted with CHDMAN from mame tools, it's perfect to store iso from systems like PSX,PS2,Dreamcast, Saturn.
RVZ can be decrypted with dolphin-tools, it's perfect to store gamecube and wii iso.

**Comment by fraganator** [comment]
Thanks for the idea. It is something I had thought about before, with Wii/GC formats like nkit and nNASOS. At that time it wasn't clear how I could make it work, as LaunchBox will only run 7z.exe (and by extension this plugin) if the rom file extension is 7z, zip, or rar. Any other file extensions are passed straight to the emulator.

I've got code in place now that allows 7z.exe to run regardless of file extension, so it might be worth revisiting this idea. I can see it being handy for decompressing CHDs for emulators that don't support CHDs, or where CHD performance isn't quite as good as an uncompressed disc image.
