### ISSUE TITLE
Feature Request: Add Option to create xiso

### ISSUE THREAD

**Issue by ErAzOr2k** [fraganator/archive-cache-manager#34]
Hi,

Redump Xbox Isos are not supported by xemu emulator.
For this, we need to extract an xiso (many tools are available).

Is it possible to add an option in archive cache manager, to create an xiso "on the fly"?

Regards

ErAzOr

**Comment by fraganator** [comment]
Hi @ErAzOr2k, thanks for the suggestion. Are your redump xbox isos in a zip file? Just wondering if they need to be extracted first, then converted to xiso.

**Comment by MattSidney** [comment]
Hey, was going to open this same request but found this instead. 
The .iso files are in .zip files. They then need to be extracted and then converted into xiso. 
This seems possible via the https://github.com/XboxDev/extract-xiso tool. 

So steps might be:
- extract zip to local. 
- use xiso to extract to folder: `.\extract-xiso.exe -d 'Directory' -x 'FILE.iso'` 
- use xiso to create xiso: `.\extract-xiso.exe -c 'Directory'`

Let me know if you need someone to perform testing :)

**Comment by ErAzOr2k** [comment]
Hi and sorry for the delay. @MattSidney answered the question.

This page describes alternative methods, to create xiso: https://xemu.app/docs/disc-images/

**Comment by fraganator** [comment]
Thanks for the links and info everyone. I'll aim to include xiso support in the next release.

**Comment by fraganator** [comment]
Hi @ErAzOr2k @MattSidney 

Here's a new beta release which includes xiso conversion support: [ArchiveCacheManager.v2.14.beta1.zip](https://github.com/fraganator/archive-cache-manager/files/10219504/ArchiveCacheManager.v2.14.beta1.zip)

It can extract an iso from a zip to the cache, then convert to xiso format. It can also copy an iso to the cache, then convert to xiso format. If the iso is already in xiso format, it's simply copied to the cache.

The original rom file (zip or redump iso) won't be modified when converting to xiso. The rom is extracted or copied to the cache first, and that copy is then converted to xiso. The resulting .iso.old copy from the cache will then be deleted.

After installing the plugin, [download extract-xiso](https://github.com/XboxDev/extract-xiso/releases) and place the exe in the `LaunchBox\Plugins\ArchiveCacheManager\Extractors` folder. In the Archive Cache Manager config, add your Xbox emulator on the Extraction Settings page, and check the box in the extract-xiso column. Also make sure the emulator has the `Extract ROM archives before running` option checked in the LaunchBox emulator settings.

![image](https://user-images.githubusercontent.com/7381808/207377488-a9e942f2-e1ee-42bf-870d-82827efa0d92.png)

Please test it out and let me know if there are any issues. Thanks!

**Comment by MattSidney** [comment]
Wow, that was fast! Thanks @fraganator. 

I have tested with a coulpe of games both launching directly and by using the batch caching method. Both working great, nice work.

**Comment by ErAzOr2k** [comment]
Thank you so much.
It is working as expected. No issues so far :)

**Comment by MattSidney** [comment]
@fraganator is this something you will push into the main release?

**Comment by fraganator** [comment]
@MattSidney Thanks for the reminder, I'll put together a new release in the next day or two.

**Comment by fraganator** [comment]
Available in v2.15.
