### ISSUE TITLE
Option to ignore errors during batch cache

### ISSUE THREAD

**Issue by davis-junior** [fraganator/archive-cache-manager#37]
I skimmed the documentation and looked in the plugin settings for an option to ignore errors while batch caching multiple games. I am assuming this feature does not exist, so this is a feature request.

My use case:
I like to cache all my favorites and top games of all systems, which is somewhere in the vicinity of 20-50 games per system. This can take several hours. Currently, an error will pause the cache routine, and it will not resume until introducing some human intervention. So, e.g., on the fourth of 50 games to process, an error is thrown, leaving the PC idle until I return from work or wake up in the morning. Ideally, a checkbox option that automatically ignores these errors would eliminate the need to babysit.

Even more ideally would be to eliminate the source of all errors. Though the way I see it is: it is a moving target, and the less ideal solution of adding the option just to ignore the errors is the most practical.

**Comment by fraganator** [comment]
Hi @davis-junior , thanks for the feature request. An ignore or pause on error toggle is a good idea. I'll probably add checkbox option to the cache window itself.

In terms of any caching errors, they will be captured in the logs in the `LaunchBox\Plugins\ArchiveCacheManager\Logs` folder. Next time there is a caching error, try checking the latest log file in that folder for any obvious errors, and feel free to raise another issue here to help resolve them.

**Comment by fraganator** [comment]
This has been implemented in 405b4a7 with a _Pause Caching On Error_ checkbox in the batch cache window. The default for the checkbox is unchecked, so errors will be ignored.

![image](https://user-images.githubusercontent.com/7381808/215375529-6417ef4a-440e-4b6e-a26a-a19b3e107fe7.png)

**Comment by davis-junior** [comment]
Wow, that was fast! I'll build out the project in the coming days and give it a try.

**Comment by fraganator** [comment]
Added to release [v2.16](https://github.com/fraganator/archive-cache-manager/releases/tag/v2.16).
