### ISSUE TITLE
allow file name priority optionally, alongside file extension priority

### ISSUE THREAD

**Issue by danpowpow** [fraganator/archive-cache-manager#9]
When extracting  archives containing original xbox files for playback through cxbx reloaded, the extension required is .xbe, however there are often multiple files with that extension within the archive. Archive Cache Manager cannot currently know which file to pass to the emulator, and so most often passes the incorrect file, causing  header errors in the emulator

would it be possible, alongside the file extension priority data entry area, to have an optional file name priority data entry area?

For example, for cxbx reloaded, where  the file extension priority is '.xbe' the name priorty would be 'Default,default'

**Comment by fraganator** [comment]
Nice idea. I wonder if a more general regular expression match might be worth implementing. I'll have a play around and see what works.

**Comment by danpowpow** [comment]
Thanks for picking this up.
Regex integration would be far more flexible than my suggestion. Nice idea!
I look forward to seeing what you come up with. I'm happy to test any alpha/betas if required.

**Comment by fraganator** [comment]
Hi @danpowpow - sorry it's taken so long to get back to this. In fixing another issue (#10), I've tweaked the wildcard matching for files. Now you should be able to specify the file extension, the entire filename, or a combination of both and have them match. So for cxbx, the file extension can now be set to `default.xbe`. You can download a beta of the plugin here:

[ArchiveCacheManager.v2.0.8.debug2.zip](https://github.com/fraganator/archive-cache-manager/files/7826053/ArchiveCacheManager.v2.0.8.debug2.zip)

**Comment by danpowpow** [comment]
This is fantastic news - thanks @fraganator !
I'll test the beta and report back.
Don't worry at all about the timeframe - I'm grateful for you reviewing the issue :-)

**Comment by fraganator** [comment]
Hi @danpowpow - The [latest version](https://forums.launchbox-app.com/files/file/234-archive-cache-manager/) of the plugin has the wildcard matching included, so I'll close this issue. If you find any problems in testing please reopen it.
